// Component: RootLayout
/*----------------------------------------------------------------------------------------------------*/

/*---------- Imports ----------*/

// Components (node)
import type { Metadata } from 'next';

// Fonts
import { Inter } from 'next/font/google';

// Styles
import './globals.css';

/*---------- Static Data ----------*/

// Fonts
const inter = Inter({ subsets: ['latin'] });

// Metadata
export const metadata: Metadata = {
	title: 'Birthday Cake Generator',
	description: 'Generated by create next app',
};

/*---------- Template ----------*/

// Types
export type RootLayoutProps = Readonly<{
	children: React.ReactNode;
}>;

export default function RootLayout(props: RootLayoutProps) {
	/*----- Props -----*/

	// Destructure props
	const { children } = props;

	/*----- Init -----*/

	// Return default
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
